// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/customer_model.dart';
import 'core/models/invoice_model.dart';
import 'core/models/product_model.dart';
import 'core/models/supplier_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1276594663308789271),
    name: 'InvoiceModel',
    lastPropertyId: const obx_int.IdUid(4, 7266889188059557236),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8236654922086660569),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1478784154898671141),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6810401488571194711),
        name: 'discount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7266889188059557236),
        name: 'customerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 6785356890388700040),
        relationField: 'customer',
        relationTarget: 'CustomerModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 8285162342199049270),
        name: 'products',
        targetId: const obx_int.IdUid(3, 4994923357143891925),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4994923357143891925),
    name: 'ProductModel',
    lastPropertyId: const obx_int.IdUid(9, 8478365876763667420),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4237033166438420724),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3272995123380301104),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2978518655761932239),
        name: 'imgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3619214903314657515),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1089478170632229906),
        name: 'buyingPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3782837562990242550),
        name: 'saleingPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3835863970226262337),
        name: 'wholesalePrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8478365876763667420),
        name: 'barcode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 783840927190999926),
    name: 'SupplierModel',
    lastPropertyId: const obx_int.IdUid(5, 3511302903263425113),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7148167846214085927),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2513083801854724206),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8709564943397619488),
        name: 'storeAdd',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6963550307710833231),
        name: 'storeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3511302903263425113),
        name: 'phoneNum',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1634032733595615740),
    name: 'CustomerModel',
    lastPropertyId: const obx_int.IdUid(4, 6467277375473153351),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1852976534403239224),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6056505571447369849),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1137766993165029932),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6467277375473153351),
        name: 'phoneNum',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 6520020354248853420),
        name: 'invoices',
        targetId: const obx_int.IdUid(2, 1276594663308789271),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 1634032733595615740),
    lastIndexId: const obx_int.IdUid(1, 6785356890388700040),
    lastRelationId: const obx_int.IdUid(3, 8285162342199049270),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [6496767718804955308],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      5377542499523323171,
      4230590313682093606,
      6883808037235374245,
      1479675135453961272,
      5460954541701112104,
    ],
    retiredRelationUids: const [5744165664349237965],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    InvoiceModel: obx_int.EntityDefinition<InvoiceModel>(
      model: _entities[0],
      toOneRelations: (InvoiceModel object) => [object.customer],
      toManyRelations: (InvoiceModel object) => {
        obx_int.RelInfo<InvoiceModel>.toMany(3, object.id): object.products,
      },
      getId: (InvoiceModel object) => object.id,
      setId: (InvoiceModel object, int id) {
        object.id = id;
      },
      objectToFB: (InvoiceModel object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.date.millisecondsSinceEpoch);
        fbb.addFloat64(2, object.discount);
        fbb.addInt64(3, object.customer.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final discountParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final object = InvoiceModel(date: dateParam, discount: discountParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.customer.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.customer.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<InvoiceModel>(
          object.products,
          store,
          obx_int.RelInfo<InvoiceModel>.toMany(3, object.id),
        );
        return object;
      },
    ),
    ProductModel: obx_int.EntityDefinition<ProductModel>(
      model: _entities[1],
      toOneRelations: (ProductModel object) => [],
      toManyRelations: (ProductModel object) => {},
      getId: (ProductModel object) => object.id,
      setId: (ProductModel object, int id) {
        object.id = id;
      },
      objectToFB: (ProductModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final imgPathOffset = object.imgPath == null
            ? null
            : fbb.writeString(object.imgPath!);
        final barcodeOffset = object.barcode == null
            ? null
            : fbb.writeString(object.barcode!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, imgPathOffset);
        fbb.addInt64(3, object.quantity);
        fbb.addFloat64(4, object.buyingPrice);
        fbb.addFloat64(5, object.saleingPrice);
        fbb.addFloat64(6, object.wholesalePrice);
        fbb.addOffset(8, barcodeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final imgPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final buyingPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final saleingPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final wholesalePriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final barcodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = ProductModel(
          name: nameParam,
          imgPath: imgPathParam,
          quantity: quantityParam,
          buyingPrice: buyingPriceParam,
          saleingPrice: saleingPriceParam,
          wholesalePrice: wholesalePriceParam,
          barcode: barcodeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    SupplierModel: obx_int.EntityDefinition<SupplierModel>(
      model: _entities[2],
      toOneRelations: (SupplierModel object) => [],
      toManyRelations: (SupplierModel object) => {},
      getId: (SupplierModel object) => object.id,
      setId: (SupplierModel object, int id) {
        object.id = id;
      },
      objectToFB: (SupplierModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final storeAddOffset = object.storeAdd == null
            ? null
            : fbb.writeString(object.storeAdd!);
        final storeNameOffset = fbb.writeString(object.storeName);
        final phoneNumOffset = fbb.writeString(object.phoneNum);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, storeAddOffset);
        fbb.addOffset(3, storeNameOffset);
        fbb.addOffset(4, phoneNumOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final storeAddParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final storeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final phoneNumParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = SupplierModel(
          name: nameParam,
          storeAdd: storeAddParam,
          storeName: storeNameParam,
          phoneNum: phoneNumParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    CustomerModel: obx_int.EntityDefinition<CustomerModel>(
      model: _entities[3],
      toOneRelations: (CustomerModel object) => [],
      toManyRelations: (CustomerModel object) => {
        obx_int.RelInfo<CustomerModel>.toMany(1, object.id): object.invoices,
      },
      getId: (CustomerModel object) => object.id,
      setId: (CustomerModel object, int id) {
        object.id = id;
      },
      objectToFB: (CustomerModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final phoneNumOffset = fbb.writeString(object.phoneNum);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, addressOffset);
        fbb.addOffset(3, phoneNumOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final phoneNumParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = CustomerModel(
          name: nameParam,
          address: addressParam,
          phoneNum: phoneNumParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<CustomerModel>(
          object.invoices,
          store,
          obx_int.RelInfo<CustomerModel>.toMany(1, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [InvoiceModel] entity fields to define ObjectBox queries.
class InvoiceModel_ {
  /// See [InvoiceModel.id].
  static final id = obx.QueryIntegerProperty<InvoiceModel>(
    _entities[0].properties[0],
  );

  /// See [InvoiceModel.date].
  static final date = obx.QueryDateProperty<InvoiceModel>(
    _entities[0].properties[1],
  );

  /// See [InvoiceModel.discount].
  static final discount = obx.QueryDoubleProperty<InvoiceModel>(
    _entities[0].properties[2],
  );

  /// See [InvoiceModel.customer].
  static final customer = obx.QueryRelationToOne<InvoiceModel, CustomerModel>(
    _entities[0].properties[3],
  );

  /// see [InvoiceModel.products]
  static final products = obx.QueryRelationToMany<InvoiceModel, ProductModel>(
    _entities[0].relations[0],
  );
}

/// [ProductModel] entity fields to define ObjectBox queries.
class ProductModel_ {
  /// See [ProductModel.id].
  static final id = obx.QueryIntegerProperty<ProductModel>(
    _entities[1].properties[0],
  );

  /// See [ProductModel.name].
  static final name = obx.QueryStringProperty<ProductModel>(
    _entities[1].properties[1],
  );

  /// See [ProductModel.imgPath].
  static final imgPath = obx.QueryStringProperty<ProductModel>(
    _entities[1].properties[2],
  );

  /// See [ProductModel.quantity].
  static final quantity = obx.QueryIntegerProperty<ProductModel>(
    _entities[1].properties[3],
  );

  /// See [ProductModel.buyingPrice].
  static final buyingPrice = obx.QueryDoubleProperty<ProductModel>(
    _entities[1].properties[4],
  );

  /// See [ProductModel.saleingPrice].
  static final saleingPrice = obx.QueryDoubleProperty<ProductModel>(
    _entities[1].properties[5],
  );

  /// See [ProductModel.wholesalePrice].
  static final wholesalePrice = obx.QueryDoubleProperty<ProductModel>(
    _entities[1].properties[6],
  );

  /// See [ProductModel.barcode].
  static final barcode = obx.QueryStringProperty<ProductModel>(
    _entities[1].properties[7],
  );
}

/// [SupplierModel] entity fields to define ObjectBox queries.
class SupplierModel_ {
  /// See [SupplierModel.id].
  static final id = obx.QueryIntegerProperty<SupplierModel>(
    _entities[2].properties[0],
  );

  /// See [SupplierModel.name].
  static final name = obx.QueryStringProperty<SupplierModel>(
    _entities[2].properties[1],
  );

  /// See [SupplierModel.storeAdd].
  static final storeAdd = obx.QueryStringProperty<SupplierModel>(
    _entities[2].properties[2],
  );

  /// See [SupplierModel.storeName].
  static final storeName = obx.QueryStringProperty<SupplierModel>(
    _entities[2].properties[3],
  );

  /// See [SupplierModel.phoneNum].
  static final phoneNum = obx.QueryStringProperty<SupplierModel>(
    _entities[2].properties[4],
  );
}

/// [CustomerModel] entity fields to define ObjectBox queries.
class CustomerModel_ {
  /// See [CustomerModel.id].
  static final id = obx.QueryIntegerProperty<CustomerModel>(
    _entities[3].properties[0],
  );

  /// See [CustomerModel.name].
  static final name = obx.QueryStringProperty<CustomerModel>(
    _entities[3].properties[1],
  );

  /// See [CustomerModel.address].
  static final address = obx.QueryStringProperty<CustomerModel>(
    _entities[3].properties[2],
  );

  /// See [CustomerModel.phoneNum].
  static final phoneNum = obx.QueryStringProperty<CustomerModel>(
    _entities[3].properties[3],
  );

  /// see [CustomerModel.invoices]
  static final invoices = obx.QueryRelationToMany<CustomerModel, InvoiceModel>(
    _entities[3].relations[0],
  );
}
