// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/transactions_entry.dart';
import 'core/models/buying_invoice_model.dart';
import 'core/models/customer_model.dart';
import 'core/models/expense_model.dart';
import 'core/models/invoice_item_model.dart';
import 'core/models/product_model.dart';
import 'core/models/safe_balance_model.dart';
import 'core/models/selling_invoice_model.dart';
import 'core/models/supplier_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7404789058678390977),
    name: 'BuyingInvoiceModel',
    lastPropertyId: const obx_int.IdUid(3, 2047517275180633959),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5403220447456891180),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1478682771571383033),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2047517275180633959),
        name: 'supplierId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4375158411760175235),
        relationField: 'supplier',
        relationTarget: 'SupplierModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 7520846125968903522),
        name: 'items',
        targetId: const obx_int.IdUid(5, 7920349003692997400),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7304082577421180967),
    name: 'CustomerModel',
    lastPropertyId: const obx_int.IdUid(4, 5828514757816408244),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3981275650758356884),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3757039822699485613),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7801097240781091149),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5828514757816408244),
        name: 'phoneNum',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'invoices',
        srcEntity: 'SellingInvoiceModel',
        srcField: 'customer',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3246336924639973503),
    name: 'ExpenseModel',
    lastPropertyId: const obx_int.IdUid(4, 314900683966834625),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4380192751872788381),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6878530518767877482),
        name: 'date',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(4, 494278398425655267),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5265223614751484004),
        name: 'value',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 314900683966834625),
        name: 'note',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7920349003692997400),
    name: 'InvoiceItemModel',
    lastPropertyId: const obx_int.IdUid(6, 4199778017834988001),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1029302115826801083),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7944216224237691238),
        name: 'productId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 5355486022806276115),
        relationField: 'product',
        relationTarget: 'ProductModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4159645204281845792),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3873439576440259367),
        name: 'unitPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4199778017834988001),
        name: 'lineTotal',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 8711636882801036865),
    name: 'ProductModel',
    lastPropertyId: const obx_int.IdUid(9, 7881785610241647125),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5967723536281617424),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6801770434095823241),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 449955122709254947),
        name: 'imgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8221197678092390994),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8959589441578360164),
        name: 'buyingPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5824331283481038842),
        name: 'wholesalePrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3294482119739885208),
        name: 'barcode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7881785610241647125),
        name: 'sellingPrice',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 544091790987256582),
    name: 'SafeBalanceModel',
    lastPropertyId: const obx_int.IdUid(3, 4426982627598649372),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6662616246408707747),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1860044015515093941),
        name: 'currentBalance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4426982627598649372),
        name: 'lastUpdated',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 537983289106764398),
    name: 'SellingInvoiceModel',
    lastPropertyId: const obx_int.IdUid(4, 7281652548644004053),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1343950023051771643),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5950305306250462615),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5024482723427805621),
        name: 'discount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7281652548644004053),
        name: 'customerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 2542401844819244147),
        relationField: 'customer',
        relationTarget: 'CustomerModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 2528445483058024405),
        name: 'items',
        targetId: const obx_int.IdUid(5, 7920349003692997400),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 7408553853324572548),
    name: 'SupplierModel',
    lastPropertyId: const obx_int.IdUid(5, 5552613674113465195),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7565815217169801683),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5927160455585655689),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1716651045207733288),
        name: 'storeAdd',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3195932976521454643),
        name: 'storeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5552613674113465195),
        name: 'phoneNum',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 4619521982065349046),
    name: 'TransactionsEntry',
    lastPropertyId: const obx_int.IdUid(6, 8297995075222169350),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9185619619074211615),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5626366382907125239),
        name: 'type',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(8, 6027171614437595435),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1927919349330023791),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7646390602949430750),
        name: 'referenceId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6768180114823487599),
        name: 'timestamp',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(9, 1617320129231709899),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8297995075222169350),
        name: 'userName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 4619521982065349046),
    lastIndexId: const obx_int.IdUid(9, 1617320129231709899),
    lastRelationId: const obx_int.IdUid(3, 2528445483058024405),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [1207969961411599869],
    retiredIndexUids: const [644280928665244392],
    retiredPropertyUids: const [
      3464908874652263421,
      5166066243020365702,
      7727042965044083560,
      1543262477846497508,
      3622203093617426965,
      2840101002925301580,
      7978173406368120247,
      8338098549628054250,
      5227921985410566069,
    ],
    retiredRelationUids: const [5053591065719948882],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BuyingInvoiceModel: obx_int.EntityDefinition<BuyingInvoiceModel>(
      model: _entities[0],
      toOneRelations: (BuyingInvoiceModel object) => [object.supplier],
      toManyRelations: (BuyingInvoiceModel object) => {
        obx_int.RelInfo<BuyingInvoiceModel>.toMany(1, object.id): object.items,
      },
      getId: (BuyingInvoiceModel object) => object.id,
      setId: (BuyingInvoiceModel object, int id) {
        object.id = id;
      },
      objectToFB: (BuyingInvoiceModel object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.date.millisecondsSinceEpoch);
        fbb.addInt64(2, object.supplier.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final object = BuyingInvoiceModel(date: dateParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.supplier.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.supplier.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<BuyingInvoiceModel>(
          object.items,
          store,
          obx_int.RelInfo<BuyingInvoiceModel>.toMany(1, object.id),
        );
        return object;
      },
    ),
    CustomerModel: obx_int.EntityDefinition<CustomerModel>(
      model: _entities[1],
      toOneRelations: (CustomerModel object) => [],
      toManyRelations: (CustomerModel object) => {
        obx_int.RelInfo<SellingInvoiceModel>.toOneBacklink(
          4,
          object.id,
          (SellingInvoiceModel srcObject) => srcObject.customer,
        ): object.invoices,
      },
      getId: (CustomerModel object) => object.id,
      setId: (CustomerModel object, int id) {
        object.id = id;
      },
      objectToFB: (CustomerModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final phoneNumOffset = fbb.writeString(object.phoneNum);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, addressOffset);
        fbb.addOffset(3, phoneNumOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final phoneNumParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = CustomerModel(
          name: nameParam,
          address: addressParam,
          phoneNum: phoneNumParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<CustomerModel>(
          object.invoices,
          store,
          obx_int.RelInfo<SellingInvoiceModel>.toOneBacklink(
            4,
            object.id,
            (SellingInvoiceModel srcObject) => srcObject.customer,
          ),
        );
        return object;
      },
    ),
    ExpenseModel: obx_int.EntityDefinition<ExpenseModel>(
      model: _entities[2],
      toOneRelations: (ExpenseModel object) => [],
      toManyRelations: (ExpenseModel object) => {},
      getId: (ExpenseModel object) => object.id,
      setId: (ExpenseModel object, int id) {
        object.id = id;
      },
      objectToFB: (ExpenseModel object, fb.Builder fbb) {
        final noteOffset = fbb.writeString(object.note);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.date.millisecondsSinceEpoch);
        fbb.addFloat64(2, object.value);
        fbb.addOffset(3, noteOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final valueParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = ExpenseModel(
          date: dateParam,
          value: valueParam,
          note: noteParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    InvoiceItemModel: obx_int.EntityDefinition<InvoiceItemModel>(
      model: _entities[3],
      toOneRelations: (InvoiceItemModel object) => [object.product],
      toManyRelations: (InvoiceItemModel object) => {},
      getId: (InvoiceItemModel object) => object.id,
      setId: (InvoiceItemModel object, int id) {
        object.id = id;
      },
      objectToFB: (InvoiceItemModel object, fb.Builder fbb) {
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.product.targetId);
        fbb.addInt64(3, object.quantity);
        fbb.addFloat64(4, object.unitPrice);
        fbb.addFloat64(5, object.lineTotal);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final unitPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final lineTotalParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = InvoiceItemModel(
          quantity: quantityParam,
          unitPrice: unitPriceParam,
          lineTotal: lineTotalParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.product.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.product.attach(store);
        return object;
      },
    ),
    ProductModel: obx_int.EntityDefinition<ProductModel>(
      model: _entities[4],
      toOneRelations: (ProductModel object) => [],
      toManyRelations: (ProductModel object) => {},
      getId: (ProductModel object) => object.id,
      setId: (ProductModel object, int id) {
        object.id = id;
      },
      objectToFB: (ProductModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final imgPathOffset = object.imgPath == null
            ? null
            : fbb.writeString(object.imgPath!);
        final barcodeOffset = object.barcode == null
            ? null
            : fbb.writeString(object.barcode!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, imgPathOffset);
        fbb.addInt64(3, object.quantity);
        fbb.addFloat64(4, object.buyingPrice);
        fbb.addFloat64(6, object.wholesalePrice);
        fbb.addOffset(7, barcodeOffset);
        fbb.addFloat64(8, object.sellingPrice);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final imgPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final buyingPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final sellingPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final wholesalePriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final barcodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final object = ProductModel(
          name: nameParam,
          imgPath: imgPathParam,
          quantity: quantityParam,
          buyingPrice: buyingPriceParam,
          sellingPrice: sellingPriceParam,
          wholesalePrice: wholesalePriceParam,
          barcode: barcodeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    SafeBalanceModel: obx_int.EntityDefinition<SafeBalanceModel>(
      model: _entities[5],
      toOneRelations: (SafeBalanceModel object) => [],
      toManyRelations: (SafeBalanceModel object) => {},
      getId: (SafeBalanceModel object) => object.id,
      setId: (SafeBalanceModel object, int id) {
        object.id = id;
      },
      objectToFB: (SafeBalanceModel object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.currentBalance);
        fbb.addInt64(2, object.lastUpdated.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final currentBalanceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = SafeBalanceModel(
          currentBalance: currentBalanceParam,
          lastUpdated: lastUpdatedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    SellingInvoiceModel: obx_int.EntityDefinition<SellingInvoiceModel>(
      model: _entities[6],
      toOneRelations: (SellingInvoiceModel object) => [object.customer],
      toManyRelations: (SellingInvoiceModel object) => {
        obx_int.RelInfo<SellingInvoiceModel>.toMany(3, object.id): object.items,
      },
      getId: (SellingInvoiceModel object) => object.id,
      setId: (SellingInvoiceModel object, int id) {
        object.id = id;
      },
      objectToFB: (SellingInvoiceModel object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.date.millisecondsSinceEpoch);
        fbb.addFloat64(2, object.discount);
        fbb.addInt64(3, object.customer.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final discountParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final object = SellingInvoiceModel(
          date: dateParam,
          discount: discountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.customer.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.customer.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<SellingInvoiceModel>(
          object.items,
          store,
          obx_int.RelInfo<SellingInvoiceModel>.toMany(3, object.id),
        );
        return object;
      },
    ),
    SupplierModel: obx_int.EntityDefinition<SupplierModel>(
      model: _entities[7],
      toOneRelations: (SupplierModel object) => [],
      toManyRelations: (SupplierModel object) => {},
      getId: (SupplierModel object) => object.id,
      setId: (SupplierModel object, int id) {
        object.id = id;
      },
      objectToFB: (SupplierModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final storeAddOffset = object.storeAdd == null
            ? null
            : fbb.writeString(object.storeAdd!);
        final storeNameOffset = fbb.writeString(object.storeName);
        final phoneNumOffset = fbb.writeString(object.phoneNum);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, storeAddOffset);
        fbb.addOffset(3, storeNameOffset);
        fbb.addOffset(4, phoneNumOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final storeAddParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final storeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final phoneNumParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = SupplierModel(
          name: nameParam,
          storeAdd: storeAddParam,
          storeName: storeNameParam,
          phoneNum: phoneNumParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    TransactionsEntry: obx_int.EntityDefinition<TransactionsEntry>(
      model: _entities[8],
      toOneRelations: (TransactionsEntry object) => [],
      toManyRelations: (TransactionsEntry object) => {},
      getId: (TransactionsEntry object) => object.id,
      setId: (TransactionsEntry object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionsEntry object, fb.Builder fbb) {
        final userNameOffset = object.userName == null
            ? null
            : fbb.writeString(object.userName!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.type);
        fbb.addFloat64(2, object.amount);
        fbb.addInt64(3, object.referenceId);
        fbb.addInt64(4, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(5, userNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final typeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final referenceIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final userNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = TransactionsEntry(
          type: typeParam,
          amount: amountParam,
          referenceId: referenceIdParam,
          timestamp: timestampParam,
          userName: userNameParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BuyingInvoiceModel] entity fields to define ObjectBox queries.
class BuyingInvoiceModel_ {
  /// See [BuyingInvoiceModel.id].
  static final id = obx.QueryIntegerProperty<BuyingInvoiceModel>(
    _entities[0].properties[0],
  );

  /// See [BuyingInvoiceModel.date].
  static final date = obx.QueryDateProperty<BuyingInvoiceModel>(
    _entities[0].properties[1],
  );

  /// See [BuyingInvoiceModel.supplier].
  static final supplier =
      obx.QueryRelationToOne<BuyingInvoiceModel, SupplierModel>(
        _entities[0].properties[2],
      );

  /// see [BuyingInvoiceModel.items]
  static final items =
      obx.QueryRelationToMany<BuyingInvoiceModel, InvoiceItemModel>(
        _entities[0].relations[0],
      );
}

/// [CustomerModel] entity fields to define ObjectBox queries.
class CustomerModel_ {
  /// See [CustomerModel.id].
  static final id = obx.QueryIntegerProperty<CustomerModel>(
    _entities[1].properties[0],
  );

  /// See [CustomerModel.name].
  static final name = obx.QueryStringProperty<CustomerModel>(
    _entities[1].properties[1],
  );

  /// See [CustomerModel.address].
  static final address = obx.QueryStringProperty<CustomerModel>(
    _entities[1].properties[2],
  );

  /// See [CustomerModel.phoneNum].
  static final phoneNum = obx.QueryStringProperty<CustomerModel>(
    _entities[1].properties[3],
  );

  /// see [CustomerModel.invoices]
  static final invoices =
      obx.QueryBacklinkToMany<SellingInvoiceModel, CustomerModel>(
        SellingInvoiceModel_.customer,
      );
}

/// [ExpenseModel] entity fields to define ObjectBox queries.
class ExpenseModel_ {
  /// See [ExpenseModel.id].
  static final id = obx.QueryIntegerProperty<ExpenseModel>(
    _entities[2].properties[0],
  );

  /// See [ExpenseModel.date].
  static final date = obx.QueryDateProperty<ExpenseModel>(
    _entities[2].properties[1],
  );

  /// See [ExpenseModel.value].
  static final value = obx.QueryDoubleProperty<ExpenseModel>(
    _entities[2].properties[2],
  );

  /// See [ExpenseModel.note].
  static final note = obx.QueryStringProperty<ExpenseModel>(
    _entities[2].properties[3],
  );
}

/// [InvoiceItemModel] entity fields to define ObjectBox queries.
class InvoiceItemModel_ {
  /// See [InvoiceItemModel.id].
  static final id = obx.QueryIntegerProperty<InvoiceItemModel>(
    _entities[3].properties[0],
  );

  /// See [InvoiceItemModel.product].
  static final product = obx.QueryRelationToOne<InvoiceItemModel, ProductModel>(
    _entities[3].properties[1],
  );

  /// See [InvoiceItemModel.quantity].
  static final quantity = obx.QueryIntegerProperty<InvoiceItemModel>(
    _entities[3].properties[2],
  );

  /// See [InvoiceItemModel.unitPrice].
  static final unitPrice = obx.QueryDoubleProperty<InvoiceItemModel>(
    _entities[3].properties[3],
  );

  /// See [InvoiceItemModel.lineTotal].
  static final lineTotal = obx.QueryDoubleProperty<InvoiceItemModel>(
    _entities[3].properties[4],
  );
}

/// [ProductModel] entity fields to define ObjectBox queries.
class ProductModel_ {
  /// See [ProductModel.id].
  static final id = obx.QueryIntegerProperty<ProductModel>(
    _entities[4].properties[0],
  );

  /// See [ProductModel.name].
  static final name = obx.QueryStringProperty<ProductModel>(
    _entities[4].properties[1],
  );

  /// See [ProductModel.imgPath].
  static final imgPath = obx.QueryStringProperty<ProductModel>(
    _entities[4].properties[2],
  );

  /// See [ProductModel.quantity].
  static final quantity = obx.QueryIntegerProperty<ProductModel>(
    _entities[4].properties[3],
  );

  /// See [ProductModel.buyingPrice].
  static final buyingPrice = obx.QueryDoubleProperty<ProductModel>(
    _entities[4].properties[4],
  );

  /// See [ProductModel.wholesalePrice].
  static final wholesalePrice = obx.QueryDoubleProperty<ProductModel>(
    _entities[4].properties[5],
  );

  /// See [ProductModel.barcode].
  static final barcode = obx.QueryStringProperty<ProductModel>(
    _entities[4].properties[6],
  );

  /// See [ProductModel.sellingPrice].
  static final sellingPrice = obx.QueryDoubleProperty<ProductModel>(
    _entities[4].properties[7],
  );
}

/// [SafeBalanceModel] entity fields to define ObjectBox queries.
class SafeBalanceModel_ {
  /// See [SafeBalanceModel.id].
  static final id = obx.QueryIntegerProperty<SafeBalanceModel>(
    _entities[5].properties[0],
  );

  /// See [SafeBalanceModel.currentBalance].
  static final currentBalance = obx.QueryDoubleProperty<SafeBalanceModel>(
    _entities[5].properties[1],
  );

  /// See [SafeBalanceModel.lastUpdated].
  static final lastUpdated = obx.QueryDateProperty<SafeBalanceModel>(
    _entities[5].properties[2],
  );
}

/// [SellingInvoiceModel] entity fields to define ObjectBox queries.
class SellingInvoiceModel_ {
  /// See [SellingInvoiceModel.id].
  static final id = obx.QueryIntegerProperty<SellingInvoiceModel>(
    _entities[6].properties[0],
  );

  /// See [SellingInvoiceModel.date].
  static final date = obx.QueryDateProperty<SellingInvoiceModel>(
    _entities[6].properties[1],
  );

  /// See [SellingInvoiceModel.discount].
  static final discount = obx.QueryDoubleProperty<SellingInvoiceModel>(
    _entities[6].properties[2],
  );

  /// See [SellingInvoiceModel.customer].
  static final customer =
      obx.QueryRelationToOne<SellingInvoiceModel, CustomerModel>(
        _entities[6].properties[3],
      );

  /// see [SellingInvoiceModel.items]
  static final items =
      obx.QueryRelationToMany<SellingInvoiceModel, InvoiceItemModel>(
        _entities[6].relations[0],
      );
}

/// [SupplierModel] entity fields to define ObjectBox queries.
class SupplierModel_ {
  /// See [SupplierModel.id].
  static final id = obx.QueryIntegerProperty<SupplierModel>(
    _entities[7].properties[0],
  );

  /// See [SupplierModel.name].
  static final name = obx.QueryStringProperty<SupplierModel>(
    _entities[7].properties[1],
  );

  /// See [SupplierModel.storeAdd].
  static final storeAdd = obx.QueryStringProperty<SupplierModel>(
    _entities[7].properties[2],
  );

  /// See [SupplierModel.storeName].
  static final storeName = obx.QueryStringProperty<SupplierModel>(
    _entities[7].properties[3],
  );

  /// See [SupplierModel.phoneNum].
  static final phoneNum = obx.QueryStringProperty<SupplierModel>(
    _entities[7].properties[4],
  );
}

/// [TransactionsEntry] entity fields to define ObjectBox queries.
class TransactionsEntry_ {
  /// See [TransactionsEntry.id].
  static final id = obx.QueryIntegerProperty<TransactionsEntry>(
    _entities[8].properties[0],
  );

  /// See [TransactionsEntry.type].
  static final type = obx.QueryIntegerProperty<TransactionsEntry>(
    _entities[8].properties[1],
  );

  /// See [TransactionsEntry.amount].
  static final amount = obx.QueryDoubleProperty<TransactionsEntry>(
    _entities[8].properties[2],
  );

  /// See [TransactionsEntry.referenceId].
  static final referenceId = obx.QueryIntegerProperty<TransactionsEntry>(
    _entities[8].properties[3],
  );

  /// See [TransactionsEntry.timestamp].
  static final timestamp = obx.QueryDateProperty<TransactionsEntry>(
    _entities[8].properties[4],
  );

  /// See [TransactionsEntry.userName].
  static final userName = obx.QueryStringProperty<TransactionsEntry>(
    _entities[8].properties[5],
  );
}
